### ISSUE TITLE
Absence of navbar

### ISSUE THREAD

**Issue by Aman0-3-0Dixit** [dsc-jiit-128/Hacktober_Website_22#10]
Add a navbar at the top of the website with a complimenting appearance with the website

**Comment by amyra98** [comment]
Can you assign me this issue and also mention which components do you want in the navbar?
@Aman0-3-0Dixit

**Comment by ASAN-11** [comment]
Hello dsc-jiit-128! Can u pls assign me this issue and u can also mention the contents you want in navbar and the webpage?

**Comment by Aman0-3-0Dixit** [comment]
@amyra98 and @ASAN-11 and everyone coming for this issue , guys fix the issue using your imagination insert the content that you think should be there there are no limitations . When you will create pull requests , after that we will review what you have done... so you are free to customise as you want

**Comment by amyra98** [comment]
I have created the pull request 
Responsive Navbar #10 #17
Please merge it under hacktoberfest22 @Aman0-3-0Dixit

**Comment by IAmAnonymousAryan07** [comment]
I have created the pull request for the responsive and updated navbar 
please merge it under hacktoberfest22 @Aman0-3-0Dixit
