### ISSUE TITLE
Make the Navbar slide down when open in reduced size

### ISSUE THREAD

**Issue by Aman0-3-0Dixit** [dsc-jiit-128/Hacktober_Website_22#18]
![Screenshot (88)](https://user-images.githubusercontent.com/107999424/193830393-92780cdb-e036-4a3c-939c-c99c6c141118.png)

**Comment by tanishk-23** [comment]
@Aman0-3-0Dixit can you please assign this issue to me?

**Comment by Aman0-3-0Dixit** [comment]
@MajorReact  i will assign this issue to you tomorrow if i don't get submission from @tanishk-23 .
