### ISSUE TITLE
Eliminate the unnecessary empty space in the website and add a Contact Us Form 

### ISSUE THREAD

**Issue by Aman0-3-0Dixit** [dsc-jiit-128/Hacktober_Website_22#20]

**Comment by BharatChotwani** [comment]
Hello @Aman0-3-0Dixit, Please assign this work to me.

**Comment by Suraif16** [comment]
Hello can I solve this issue

**Comment by Aman0-3-0Dixit** [comment]
@Suraif16 i will assign this issue to you tomorrow if i don't get submission from @BharatChotwani.

**Comment by IAmAnonymousAryan07** [comment]
@Aman0-3-0Dixit i have made the contact and about form please see to it and when we click on the about or contact form then we direct to a new page hence the site is responsive . please merge it .

**Comment by Aman0-3-0Dixit** [comment]
@BharatChotwani @Suraif16 @IAmAnonymousAryan07  guys check the codebase again , it is being updated . You can work using the new codebase but this time after making changes , take the screenshots of the whole website and add alongside showing your contributions. Also make sure that your contribution should not disrupt the other unrelated elements of the website.

**Comment by IAmAnonymousAryan07** [comment]
@Aman0-3-0Dixit i have made the contact us and about and chapter and upcoming events file please see to it and when we click on the about or contact us or chapter and upcoming events links then we direct to a new page hence the site is responsive . please merge it . And also i have uploaded the screen shot while creating the pull request please see to it

**Comment by IAmAnonymousAryan07** [comment]
@Aman0-3-0Dixit i have made the contact us and about and chapter and file please see to it and when we click on the about or contact us or chapter links then we direct to a new page hence the site is responsive . please merge it . And also i have uploaded the screen shot while creating the pull request please see to it
