### ISSUE TITLE
The Google logo is to be added with some kind of animation.

### ISSUE THREAD

**Issue by justhappyuknow** [dsc-jiit-128/Hacktober_Website_22#32]

**Comment by IAmAnonymousAryan07** [comment]
@justhappyuknow where do you we need to add this logo ?

**Comment by justhappyuknow** [comment]
> 

You can add it beside the GDSC heading with linear motion

**Comment by Suraif16** [comment]
Added the logo and made the PR

**Comment by dhawalbisht** [comment]
Can you assign me this issue?
