### ISSUE TITLE
reactor the codebase

### ISSUE THREAD

**Issue by deadaf** [dsc-jiit-128/Hacktober_Website_22#37]
this repo requires refactoring of the code & all the files. 
The images & fonts too deserve a separate directory.

**Comment by deadaf** [comment]
I want to be assigned for this task.

**Comment by Aman0-3-0Dixit** [comment]
@deadaf check the codebase again , it is being updated . You can work using the new codebase but this time after making changes , take the screenshots of the whole website and add alongside in the pull request to make sure that your contribution should not disrupt the website. I have assigned this issue to you.

**Comment by deadaf** [comment]
sure , also pls add `hacktoberfest` label to this issue.
