### ISSUE TITLE
create upcoming events page

### ISSUE THREAD

**Issue by JulianaSau** [dsc-jiit-128/Hacktober_Website_22#39]
I'd like to work on the upcoming events page UI Design under hacktoberfest. Please assign me this issue

**Comment by Aman0-3-0Dixit** [comment]
@JulianaSau check the codebase again , it is being updated . You can work using the new codebase but this time after making changes , take the screenshots of the whole website and add alongside showing your contributions. Also make sure that your contribution should not disrupt the other unrelated elements of the website. I am assigning this issue to you.

**Comment by JulianaSau** [comment]
Noted. I'll make sure I don't disrupt any unrelated files
