### ISSUE TITLE
Uneven Image and Font sizes

### ISSUE THREAD

**Issue by Aman0-3-0Dixit** [dsc-jiit-128/Hacktober_Website_22#6]
Fix the issues according to your imagination

![Screenshot (77)](https://user-images.githubusercontent.com/107999424/193582924-d9e3d0ca-2374-4cef-a4bc-1be4ba415774.png)
![Screenshot (78)](https://user-images.githubusercontent.com/107999424/193583278-137d8bc5-f226-4ee1-9e22-c2efa4f26678.png)
![Screenshot (79)](https://user-images.githubusercontent.com/107999424/193583488-92d13f44-d6f6-4977-ad42-e30d7d35daa1.png)

**Comment by fosa-ij** [comment]
Hi good day, I'd like to work on this issue. How can I get myself assigned?

**Comment by Suraif16** [comment]
Hello Can I solve this issue

**Comment by Aman0-3-0Dixit** [comment]
@Suraif16 actually this issue is being assigned to @fosa-ij as he came earlier than you. But no loss, for time being you can choose other issues where there is no one assigned till now. Comment me I will assign you but do it fast

**Comment by fosa-ij** [comment]
Hi @Aman0-3-0Dixit please check out the pull request I made on this issue
