### ISSUE TITLE
Wrong and non-sensical texts present

### ISSUE THREAD

**Issue by Aman0-3-0Dixit** [dsc-jiit-128/Hacktober_Website_22#7]
Correct the misspelled words , remove non-sensical texts and add content on your own.

**Comment by xoxo16** [comment]
can i work on this issue

**Comment by nomaalam** [comment]
Hey, I want to work on this issue. Please assign it to me.

**Comment by IAmAnonymousAryan07** [comment]
I have resolved this issue . Please check and and merge it with the main branch @Aman0-3-0Dixit thanks
